using Microsoft.Data.Sqlite;
using PokemonROI.Models;
namespace PokemonROI.Services;
public sealed class AppDatabase : IDisposable
{
 public string Folder {get;}=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"PokemonROI");
 private string FilePath=>Path.Combine(Folder,"pokemonroi.db"); private SqliteConnection Open(){var c=new SqliteConnection($"Data Source={FilePath}");c.Open();return c;}
 public void Initialize(){Directory.CreateDirectory(Folder);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="CREATE TABLE IF NOT EXISTS portfolio(id INTEGER PRIMARY KEY,card_id TEXT,card_name TEXT,set_name TEXT,grade TEXT,quantity INTEGER,purchase_price TEXT,purchase_date TEXT,current_price TEXT,notes TEXT); CREATE TABLE IF NOT EXISTS cache(key TEXT PRIMARY KEY,value TEXT,updated TEXT); CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);";cmd.ExecuteNonQuery();}
 public List<PortfolioItem> GetPortfolio(){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,card_id,card_name,set_name,grade,quantity,purchase_price,purchase_date,current_price,notes FROM portfolio ORDER BY id DESC";using var r=cmd.ExecuteReader();var list=new List<PortfolioItem>();while(r.Read())list.Add(new(){Id=r.GetInt64(0),CardId=r.GetString(1),CardName=r.GetString(2),SetName=r.GetString(3),Grade=r.GetString(4),Quantity=r.GetInt32(5),PurchasePrice=decimal.Parse(r.GetString(6)),PurchaseDate=DateTime.Parse(r.GetString(7)),CurrentPrice=r.IsDBNull(8)?null:decimal.Parse(r.GetString(8)),Notes=r.GetString(9)});return list;}
 public void Save(PortfolioItem x){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText=x.Id==0?"INSERT INTO portfolio(card_id,card_name,set_name,grade,quantity,purchase_price,purchase_date,current_price,notes) VALUES($i,$n,$s,$g,$q,$p,$d,$c,$o)":"UPDATE portfolio SET quantity=$q,purchase_price=$p,purchase_date=$d,current_price=$c,notes=$o WHERE id=$id";cmd.Parameters.AddWithValue("$i",x.CardId);cmd.Parameters.AddWithValue("$n",x.CardName);cmd.Parameters.AddWithValue("$s",x.SetName);cmd.Parameters.AddWithValue("$g",x.Grade);cmd.Parameters.AddWithValue("$q",x.Quantity);cmd.Parameters.AddWithValue("$p",x.PurchasePrice.ToString(System.Globalization.CultureInfo.InvariantCulture));cmd.Parameters.AddWithValue("$d",x.PurchaseDate.ToString("O"));cmd.Parameters.AddWithValue("$c",(object?)x.CurrentPrice?.ToString(System.Globalization.CultureInfo.InvariantCulture)??DBNull.Value);cmd.Parameters.AddWithValue("$o",x.Notes);if(x.Id!=0)cmd.Parameters.AddWithValue("$id",x.Id);cmd.ExecuteNonQuery();}
 public void Delete(long id){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="DELETE FROM portfolio WHERE id=$id";cmd.Parameters.AddWithValue("$id",id);cmd.ExecuteNonQuery();}
 public void Dispose(){}
}
